name: Update Major Version Tag

on:
  push:
    tags:
      - "v*"

jobs:
  update-majorver:
    permissions:
      contents: write
    name: Update Major Version Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get major version num and update tag
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          MAJOR="${VERSION%%.*}"
          git config --global user.name "Will Taylor"
          git config --global user.email "willgeorgetaylor@users.noreply.github.com"
          git tag -fa "$MAJOR" -m "Update major version tag"
          git push origin "$MAJOR" --force